### ISSUE TITLE
marketManager stopped working!?

### ISSUE THREAD

**Issue by TestniTester** [gliwka/bittrex-market#7] opened 2017-09-13 07:07 UTC
hi!
it worked like yesterday?
today i get error:
Error: "value" required in setHeader("cookie", value)

copy/paste of example here

**Comment by gliwka** [comment] 2017-09-13 09:04
Hi,

Bittrex disabled cloudflare again. I've added a check so the library works with and without cloud flare.

Please update to version 2.1.4.

Best,
Matthias

**Comment by TestniTester** [comment] 2017-09-13 09:41
Thank you!
but 
makretManager.stop()
or
makretManager.close()
give me error?
how can i disconnect the mannager or better said.. disconnect the bittrex feed ?

**Comment by gliwka** [comment] 2017-09-13 10:00
marketManager.reset() should do what you want.

**Comment by TestniTester** [comment] 2017-09-13 10:15
marketManager.reset() 
throws error and brakes

**Comment by gliwka** [comment] 2017-09-13 10:16
Can you post the error here?

**Comment by TestniTester** [comment] 2017-09-13 10:19
![image](https://user-images.githubusercontent.com/29655426/30372350-d0bf3b80-987d-11e7-9ed9-6f6a8103546e.png)

**Comment by gliwka** [comment] 2017-09-13 11:11
Thanks. I'll roll out a fix for this race condition later in the evening.

**Comment by gliwka** [comment] 2017-09-24 09:55
Sorry for the delay, I'll try to get it sorted out today.

**Comment by gliwka** [comment] 2017-11-09 20:46
Duplicate of #20 - will continue to fix the error in that issue.

**Closed by gliwka** 2017-11-09 20:46 UTC
Labels: bug
