### ISSUE TITLE
node throws error end exits?

### ISSUE THREAD

**Issue by TestniTester** [gliwka/bittrex-market#15] opened 2017-09-28 02:28 UTC
hey,
first great work you have done....!
but from time to time when trying to connect to bittrex
the bitrex-market throws an error (on connection) and the enire node brakes and exits
is it possible this to be fixed?

**Comment by gliwka** [comment] 2017-11-09 20:50
Duplicate of #21.

**Closed by gliwka** 2017-11-09 20:50 UTC
